[tool.ruff]
# Formato de línea
line-length = 88
target-version = "py312" # Asegúrate de que coincida con tu versión de Python

# Reglas de linting
[tool.ruff.lint]
select = [
    "E",  # pycodestyle - Errores de sintaxis y estilo.
    "F",  # pyflakes - Errores no usados.
    "I",  # isort - Organización de importaciones.
    "W",  # pycodestyle - Advertencias.
    "C4", # flake8-comprehensions - Uso de compresiones.
    "N",  # pep8-naming - Nombres de variables y clases.
]

# Ignorar reglas específicas
ignore = [
    "E501",  # Ignora la longitud de línea predeterminada (si line-length no es mayor).
]

# Excluir archivos y carpetas
exclude = [
    "__init__.py", # No aplica a Ruff, pero es buena práctica en general
    # "mi_proyecto/src/legacy_code.py", # Puedes ignorar archivos viejos.
]

# Configuración específica para el formateador (incluye Jupyter)
[tool.ruff.format]
quote-style = "double"
indent-style = "space"